/* tslint:disable */
/* eslint-disable */
/**
 * Trello Clone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BoardMember } from '../model';
// @ts-ignore
import { BoardMemberListResponse } from '../model';
// @ts-ignore
import { CreateBoardMember } from '../model';
// @ts-ignore
import { ErrorResponse } from '../model';
// @ts-ignore
import { UpdateBoardMember } from '../model';
/**
 * BoardMembersApi - axios parameter creator
 * @export
 */
export const BoardMembersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete board member by ID
         * @summary Delete By ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteApiAuthenticatedBoardMembersId: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteApiAuthenticatedBoardMembersId', 'id', id)
            const localVarPath = `/api/authenticated/boardMembers/{Id}`
                .replace(`{${"Id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all board members on the system
         * @summary Get All
         * @param {number} page 
         * @param {number} limit 
         * @param {string} [expand] 
         * @param {string} [embed] 
         * @param {string} [q] 
         * @param {string} [boardId] 
         * @param {string} [userId] 
         * @param {string} [sort] 
         * @param {string} [order] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApiAuthenticatedBoardMembers: async (page: number, limit: number, expand?: string, embed?: string, q?: string, boardId?: string, userId?: string, sort?: string, order?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            assertParamExists('getApiAuthenticatedBoardMembers', 'page', page)
            // verify required parameter 'limit' is not null or undefined
            assertParamExists('getApiAuthenticatedBoardMembers', 'limit', limit)
            const localVarPath = `/api/authenticated/boardMembers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (page !== undefined) {
                localVarQueryParameter['_page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['_limit'] = limit;
            }

            if (expand !== undefined) {
                localVarQueryParameter['_expand'] = expand;
            }

            if (embed !== undefined) {
                localVarQueryParameter['_embed'] = embed;
            }

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (boardId !== undefined) {
                localVarQueryParameter['boardId'] = boardId;
            }

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (sort !== undefined) {
                localVarQueryParameter['_sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['_order'] = order;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get board member by ID
         * @summary Get By ID
         * @param {string} id 
         * @param {string} [expand] 
         * @param {string} [embed] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApiAuthenticatedBoardMembersId: async (id: string, expand?: string, embed?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getApiAuthenticatedBoardMembersId', 'id', id)
            const localVarPath = `/api/authenticated/boardMembers/{Id}`
                .replace(`{${"Id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (expand !== undefined) {
                localVarQueryParameter['_expand'] = expand;
            }

            if (embed !== undefined) {
                localVarQueryParameter['_embed'] = embed;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update board member by ID
         * @summary Update By ID
         * @param {string} id 
         * @param {UpdateBoardMember} [updateBoardMember] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchApiAuthenticatedBoardMembersId: async (id: string, updateBoardMember?: UpdateBoardMember, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('patchApiAuthenticatedBoardMembersId', 'id', id)
            const localVarPath = `/api/authenticated/boardMembers/{Id}`
                .replace(`{${"Id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateBoardMember, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a board member
         * @summary Create
         * @param {CreateBoardMember} [createBoardMember] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postApiAuthenticatedBoardMembers: async (createBoardMember?: CreateBoardMember, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/authenticated/boardMembers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBoardMember, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BoardMembersApi - functional programming interface
 * @export
 */
export const BoardMembersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BoardMembersApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete board member by ID
         * @summary Delete By ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteApiAuthenticatedBoardMembersId(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteApiAuthenticatedBoardMembersId(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get all board members on the system
         * @summary Get All
         * @param {number} page 
         * @param {number} limit 
         * @param {string} [expand] 
         * @param {string} [embed] 
         * @param {string} [q] 
         * @param {string} [boardId] 
         * @param {string} [userId] 
         * @param {string} [sort] 
         * @param {string} [order] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApiAuthenticatedBoardMembers(page: number, limit: number, expand?: string, embed?: string, q?: string, boardId?: string, userId?: string, sort?: string, order?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BoardMemberListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApiAuthenticatedBoardMembers(page, limit, expand, embed, q, boardId, userId, sort, order, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get board member by ID
         * @summary Get By ID
         * @param {string} id 
         * @param {string} [expand] 
         * @param {string} [embed] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApiAuthenticatedBoardMembersId(id: string, expand?: string, embed?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BoardMember>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApiAuthenticatedBoardMembersId(id, expand, embed, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Update board member by ID
         * @summary Update By ID
         * @param {string} id 
         * @param {UpdateBoardMember} [updateBoardMember] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchApiAuthenticatedBoardMembersId(id: string, updateBoardMember?: UpdateBoardMember, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BoardMember>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchApiAuthenticatedBoardMembersId(id, updateBoardMember, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Create a board member
         * @summary Create
         * @param {CreateBoardMember} [createBoardMember] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postApiAuthenticatedBoardMembers(createBoardMember?: CreateBoardMember, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BoardMember>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postApiAuthenticatedBoardMembers(createBoardMember, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * BoardMembersApi - factory interface
 * @export
 */
export const BoardMembersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BoardMembersApiFp(configuration)
    return {
        /**
         * Delete board member by ID
         * @summary Delete By ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteApiAuthenticatedBoardMembersId(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteApiAuthenticatedBoardMembersId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all board members on the system
         * @summary Get All
         * @param {number} page 
         * @param {number} limit 
         * @param {string} [expand] 
         * @param {string} [embed] 
         * @param {string} [q] 
         * @param {string} [boardId] 
         * @param {string} [userId] 
         * @param {string} [sort] 
         * @param {string} [order] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApiAuthenticatedBoardMembers(page: number, limit: number, expand?: string, embed?: string, q?: string, boardId?: string, userId?: string, sort?: string, order?: string, options?: any): AxiosPromise<BoardMemberListResponse> {
            return localVarFp.getApiAuthenticatedBoardMembers(page, limit, expand, embed, q, boardId, userId, sort, order, options).then((request) => request(axios, basePath));
        },
        /**
         * Get board member by ID
         * @summary Get By ID
         * @param {string} id 
         * @param {string} [expand] 
         * @param {string} [embed] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApiAuthenticatedBoardMembersId(id: string, expand?: string, embed?: string, options?: any): AxiosPromise<BoardMember> {
            return localVarFp.getApiAuthenticatedBoardMembersId(id, expand, embed, options).then((request) => request(axios, basePath));
        },
        /**
         * Update board member by ID
         * @summary Update By ID
         * @param {string} id 
         * @param {UpdateBoardMember} [updateBoardMember] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchApiAuthenticatedBoardMembersId(id: string, updateBoardMember?: UpdateBoardMember, options?: any): AxiosPromise<BoardMember> {
            return localVarFp.patchApiAuthenticatedBoardMembersId(id, updateBoardMember, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a board member
         * @summary Create
         * @param {CreateBoardMember} [createBoardMember] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postApiAuthenticatedBoardMembers(createBoardMember?: CreateBoardMember, options?: any): AxiosPromise<BoardMember> {
            return localVarFp.postApiAuthenticatedBoardMembers(createBoardMember, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BoardMembersApi - interface
 * @export
 * @interface BoardMembersApi
 */
export interface BoardMembersApiInterface {
    /**
     * Delete board member by ID
     * @summary Delete By ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardMembersApiInterface
     */
    deleteApiAuthenticatedBoardMembersId(id: string, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * Get all board members on the system
     * @summary Get All
     * @param {number} page 
     * @param {number} limit 
     * @param {string} [expand] 
     * @param {string} [embed] 
     * @param {string} [q] 
     * @param {string} [boardId] 
     * @param {string} [userId] 
     * @param {string} [sort] 
     * @param {string} [order] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardMembersApiInterface
     */
    getApiAuthenticatedBoardMembers(page: number, limit: number, expand?: string, embed?: string, q?: string, boardId?: string, userId?: string, sort?: string, order?: string, options?: AxiosRequestConfig): AxiosPromise<BoardMemberListResponse>;

    /**
     * Get board member by ID
     * @summary Get By ID
     * @param {string} id 
     * @param {string} [expand] 
     * @param {string} [embed] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardMembersApiInterface
     */
    getApiAuthenticatedBoardMembersId(id: string, expand?: string, embed?: string, options?: AxiosRequestConfig): AxiosPromise<BoardMember>;

    /**
     * Update board member by ID
     * @summary Update By ID
     * @param {string} id 
     * @param {UpdateBoardMember} [updateBoardMember] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardMembersApiInterface
     */
    patchApiAuthenticatedBoardMembersId(id: string, updateBoardMember?: UpdateBoardMember, options?: AxiosRequestConfig): AxiosPromise<BoardMember>;

    /**
     * Create a board member
     * @summary Create
     * @param {CreateBoardMember} [createBoardMember] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardMembersApiInterface
     */
    postApiAuthenticatedBoardMembers(createBoardMember?: CreateBoardMember, options?: AxiosRequestConfig): AxiosPromise<BoardMember>;

}

/**
 * BoardMembersApi - object-oriented interface
 * @export
 * @class BoardMembersApi
 * @extends {BaseAPI}
 */
export class BoardMembersApi extends BaseAPI implements BoardMembersApiInterface {
    /**
     * Delete board member by ID
     * @summary Delete By ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardMembersApi
     */
    public deleteApiAuthenticatedBoardMembersId(id: string, options?: AxiosRequestConfig) {
        return BoardMembersApiFp(this.configuration).deleteApiAuthenticatedBoardMembersId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all board members on the system
     * @summary Get All
     * @param {number} page 
     * @param {number} limit 
     * @param {string} [expand] 
     * @param {string} [embed] 
     * @param {string} [q] 
     * @param {string} [boardId] 
     * @param {string} [userId] 
     * @param {string} [sort] 
     * @param {string} [order] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardMembersApi
     */
    public getApiAuthenticatedBoardMembers(page: number, limit: number, expand?: string, embed?: string, q?: string, boardId?: string, userId?: string, sort?: string, order?: string, options?: AxiosRequestConfig) {
        return BoardMembersApiFp(this.configuration).getApiAuthenticatedBoardMembers(page, limit, expand, embed, q, boardId, userId, sort, order, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get board member by ID
     * @summary Get By ID
     * @param {string} id 
     * @param {string} [expand] 
     * @param {string} [embed] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardMembersApi
     */
    public getApiAuthenticatedBoardMembersId(id: string, expand?: string, embed?: string, options?: AxiosRequestConfig) {
        return BoardMembersApiFp(this.configuration).getApiAuthenticatedBoardMembersId(id, expand, embed, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update board member by ID
     * @summary Update By ID
     * @param {string} id 
     * @param {UpdateBoardMember} [updateBoardMember] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardMembersApi
     */
    public patchApiAuthenticatedBoardMembersId(id: string, updateBoardMember?: UpdateBoardMember, options?: AxiosRequestConfig) {
        return BoardMembersApiFp(this.configuration).patchApiAuthenticatedBoardMembersId(id, updateBoardMember, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a board member
     * @summary Create
     * @param {CreateBoardMember} [createBoardMember] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BoardMembersApi
     */
    public postApiAuthenticatedBoardMembers(createBoardMember?: CreateBoardMember, options?: AxiosRequestConfig) {
        return BoardMembersApiFp(this.configuration).postApiAuthenticatedBoardMembers(createBoardMember, options).then((request) => request(this.axios, this.basePath));
    }
}

