/* tslint:disable */
/* eslint-disable */
/**
 * Trello Clone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BoardColumn } from './board-column';
// May contain unused imports in some cases
// @ts-ignore
import { BoardMember } from './board-member';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * 
 * @export
 * @interface Board
 */
export interface Board {
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'visibility': BoardVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'color': string;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Array<BoardMember>}
     * @memberof Board
     */
    'boardMembers'?: Array<BoardMember>;
    /**
     * 
     * @type {Array<User>}
     * @memberof Board
     */
    'user'?: Array<User>;
    /**
     * 
     * @type {BoardColumn}
     * @memberof Board
     */
    'boardColumns'?: BoardColumn;
}

export const BoardVisibilityEnum = {
    Private: 'private',
    Public: 'public'
} as const;

export type BoardVisibilityEnum = typeof BoardVisibilityEnum[keyof typeof BoardVisibilityEnum];


