/* tslint:disable */
/* eslint-disable */
/**
 * Trello Clone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Board } from './board';
// May contain unused imports in some cases
// @ts-ignore
import { Task } from './task';

/**
 * 
 * @export
 * @interface BoardColumn
 */
export interface BoardColumn {
    /**
     * 
     * @type {string}
     * @memberof BoardColumn
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BoardColumn
     */
    'boardId': string;
    /**
     * 
     * @type {string}
     * @memberof BoardColumn
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof BoardColumn
     */
    'order': number;
    /**
     * 
     * @type {string}
     * @memberof BoardColumn
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof BoardColumn
     */
    'updatedAt'?: string | null;
    /**
     * 
     * @type {Array<Task>}
     * @memberof BoardColumn
     */
    'tasks'?: Array<Task>;
    /**
     * 
     * @type {Board}
     * @memberof BoardColumn
     */
    'board'?: Board;
}

