/* tslint:disable */
/* eslint-disable */
/**
 * Trello Clone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Board
 */
export interface Board {
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'visibility': BoardVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'color': string;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Board
     */
    'updatedAt'?: string;
}

export const BoardVisibilityEnum = {
    Private: 'private',
    Public: 'public'
} as const;

export type BoardVisibilityEnum = typeof BoardVisibilityEnum[keyof typeof BoardVisibilityEnum];


