/* tslint:disable */
/* eslint-disable */
/**
 * Trello Clone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Board } from './board';

/**
 * 
 * @export
 * @interface BoardMember
 */
export interface BoardMember {
    /**
     * 
     * @type {string}
     * @memberof BoardMember
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BoardMember
     */
    'boardId': string;
    /**
     * 
     * @type {string}
     * @memberof BoardMember
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof BoardMember
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof BoardMember
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Board}
     * @memberof BoardMember
     */
    'board'?: Board;
}

