/* tslint:disable */
/* eslint-disable */
/**
 * Trello Clone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateBoardRequest
 */
export interface CreateBoardRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBoardRequest
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBoardRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBoardRequest
     */
    'visibility': CreateBoardRequestVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateBoardRequest
     */
    'color': string;
}

export const CreateBoardRequestVisibilityEnum = {
    Public: 'public',
    Private: 'private'
} as const;

export type CreateBoardRequestVisibilityEnum = typeof CreateBoardRequestVisibilityEnum[keyof typeof CreateBoardRequestVisibilityEnum];


