/* tslint:disable */
/* eslint-disable */
/**
 * Trello Clone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BoardMember } from './board-member';
// May contain unused imports in some cases
// @ts-ignore
import { Meta } from './meta';

/**
 * 
 * @export
 * @interface GetApiAuthenticatedBoardMembers200Response
 */
export interface GetApiAuthenticatedBoardMembers200Response {
    /**
     * 
     * @type {Array<BoardMember>}
     * @memberof GetApiAuthenticatedBoardMembers200Response
     */
    'data': Array<BoardMember>;
    /**
     * 
     * @type {Meta}
     * @memberof GetApiAuthenticatedBoardMembers200Response
     */
    'meta': Meta;
}

