/* tslint:disable */
/* eslint-disable */
/**
 * Trello Clone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * 
 * @export
 * @interface PostApiAuthLogin200Response
 */
export interface PostApiAuthLogin200Response {
    /**
     * 
     * @type {string}
     * @memberof PostApiAuthLogin200Response
     */
    'accessToken': string;
    /**
     * 
     * @type {User}
     * @memberof PostApiAuthLogin200Response
     */
    'user': User;
    /**
     * 
     * @type {string}
     * @memberof PostApiAuthLogin200Response
     */
    'tokenType': string;
    /**
     * 
     * @type {string}
     * @memberof PostApiAuthLogin200Response
     */
    'expiresIn': string;
}

