/* tslint:disable */
/* eslint-disable */
/**
 * Trello Clone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateBoardMember
 */
export interface UpdateBoardMember {
    /**
     * 
     * @type {string}
     * @memberof UpdateBoardMember
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBoardMember
     */
    'boardId'?: string;
}

