/* tslint:disable */
/* eslint-disable */
/**
 * Trello Clone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateBoardRequest
 */
export interface UpdateBoardRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateBoardRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBoardRequest
     */
    'visibility'?: UpdateBoardRequestVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateBoardRequest
     */
    'color'?: string;
}

export const UpdateBoardRequestVisibilityEnum = {
    Private: 'private',
    Public: 'public'
} as const;

export type UpdateBoardRequestVisibilityEnum = typeof UpdateBoardRequestVisibilityEnum[keyof typeof UpdateBoardRequestVisibilityEnum];


